#!/bin/bash

if ! which virtualenv 2>&1 > /dev/null; then
  echo "Please install virtualenv and then run this"
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TMP_DIR="$DIR/.syncr"
if [[ ! -d $TMP_DIR ]]; then
  opts=""
  if ! which python3; then
    echo "Please install python3"
    exit 1
  else
    question="
import sys
if sys.version.startswith(\"3.4\"): sys.exit(1)
    "
    if python -c "$question"; then
      opts=" -p $(which python3)"
    fi
  fi

  if ! virtualenv $opts $TMP_DIR; then
    echo "Couldn't make the virtualenv :("
    rm -rf $TMP_DIR
    exit 1
  fi
fi

required_version=0.5.8.7.5

source $TMP_DIR/bin/activate

update=0
if ! python -c "import aws_syncr"; then
  update=1
else
  if ! python <<<"
import sys; from distutils.version import LooseVersion; from aws_syncr import VERSION
if LooseVersion(VERSION) < LooseVersion('$required_version'):
  sys.exit(1)
" 2>&1 >/dev/null; then
    update=1
  fi
fi

if (($update==1)); then
  echo "Installing aws_syncr==$required_version"
  pip install pip --upgrade
  pip install argparse
  pip install aws_syncr==$required_version

  # Or if pypi isn't working
  # pip install git+ssh://git@github.com/delfick/aws_syncr.git
fi

export AWS_SYNCR_CONFIG_FOLDER=$(python -c "import os; print(os.path.relpath('${DIR}', '$(pwd)'))")
aws_syncr "$@"

