---

harpoon_version: "0.6.5.3"

image_name_prefix: "dashing"

context:
  use_gitignore: true

folders:
  root_dir: "{config_root}/../"

images:

  deployer:
    context:
      parent_dir: "{folders.root_dir}"

      use_git_timestamps: false

    commands:
      - FROM ubuntu:14.04
      - RUN apt-get update && apt-get install -y python-pip libpython-dev libpython3-dev
      - RUN pip install virtualenv
      - ADD . /dashing/
      - WORKDIR /dashing/

    tasks:
      make_artifact:
        options:
          bash: "./dashing/deploy/bespin.sh publish_artifacts {ENV:env} app"
          env:
            - ENV
            - BUILD_NUMBER
            - GIT_COMMIT
            - "AWS_ACCESS_KEY_ID:"
            - "AWS_SECRET_ACCESS_KEY:"
            - "AWS_SECURITY_TOKEN:"
        description: "Make and upload the artifact"

