---

- name: Get me some virtualenv
  command: pip install {{item}}
  with_items:
    - virtualenv

- name: Deps for building python
  yum: name={{item}} state=present
  with_items:
    - gcc
    - zlib-devel
    - openssl-devel

- name: Get me some python3
  get_url: url=https://www.python.org/ftp/python/3.4.2/Python-3.4.2.tgz dest=/tmp/Python.tgz

- name: Make folder for python
  file: path=/tmp/Python state=directory

- name: Extract python
  unarchive: src=/tmp/Python.tgz dest=/tmp/Python
  sudo: yes

- name: configure python3
  shell: cd /tmp/Python/Python-3.4.2 && ./configure

- name: Make python3
  shell: cd /tmp/Python/Python-3.4.2 && make

- name: Install python3
  shell: cd /tmp/Python/Python-3.4.2 && sudo make install
