---

- name: Make sure we have /var/log/rea
  file: path=/var/log/rea state=directory

- name: Make sure we have /var/log/rea/dashmat
  file: path=/var/log/rea/dashmat state=directory

- name: Make sure we have compiled_prep
  file: path=/var/tmp/artifacts/dashmat/compiled_prep state=directory

- name: Make virtualenv
  shell: virtualenv-3.4 /opt/dashmat
  environment:
    PATH: /bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin

- name: Install init script
  template: src=dashmat.init dest="/etc/init/dashmat.conf" mode=755 owner=root group=root

- name: Copy in syslog
  template: src=syslog.conf dest=/etc/rsyslog.d/50-dashmat.conf
  notify: RestartSyslog

- name: Find status of the dashmat
  command: status dashmat
  register: dashmat_status
  changed_when: false

- name: stop the dashmat
  command: stop dashmat
  when: dashmat_status.stdout_lines[0] != "dashmat stop/waiting"

- name: "Start dashmat"
  command: start dashmat

