---

kms_secrets:
  splunk_password:
    kms: "<kms_encrypted>"
    location: ap-southeast-2
  cloudability_auth_token:
    kms: "<kms_encrypted>"
    location: ap-southeast-2

modules:
  kms_secrets:
    import_path: python_dashing.core_modules.amazon_base.main:AmazonBase

  index:
    import_path: python_dashing.core_modules.index.main:Index

  reviews:
    import_path: custom.reviews.main:Reviews
    server_options:
      app_id: "<app_id>"
      itunes_country_code: au

  scaling:
    import_path: custom.scaling.main:Scaling
    server_options:
      cloudability_auth_token: "{kms_secrets.cloudability_auth_token}"

      ordered_accounts: ["dev", "stg", "prod"]
      accounts:
        dev:
          account_id: "<account_id>"
          role_to_assume: role/dashing/viewer

        stg:
          account_id: "<account_id>"
          role_to_assume: role/dashing/viewer

        prod:
          account_id: "<account_id>"
          role_to_assume: role/dashing/viewer

dashboards:
  "/":
    imports:
      - [[Index, IndexItem], "index"]
    layout: |
      <Index>
        <IndexItem href="/reviews" desc="IOS Reviews Dashboard"/>
        <IndexItem href="/scaling" desc="Scaling Groups Dashboard"/>
      </Index>

  "/reviews":
    imports:
      - [[CommentsModule, ReviewsModule], "reviews"]
    layout: |
      <flexcontainer>
        <CommentsModule datasource="/data/reviews/comments" />
      </flexcontainer>
      <flexcontainer>
        <ReviewsModule datasource="/data/reviews/total_reviews" title="Total IOS Ratings"/>
        <ReviewsModule datasource="/data/reviews/current_reviews" title="Current IOS Ratings"/>
      </flexcontainer>

  "/scaling":
    imports:
      - [[ScalingModule, InstanceCountModule, CostModule], "scaling"]
    layout: |
      <flexcontainer>
        <ScalingModule datasource="/data/scaling/scaling" title="" />
      </flexcontainer>
      <flexcontainer>
        <InstanceCountModule datasource="/data/scaling/instance_count" title="Instance Count" />
        <CostModule datasource="/data/scaling/cost_last_month" title="Last month Amazon cost" />
        <CostModule datasource="/data/scaling/cost_this_month" title="This month Amazon cost" />
      </flexcontainer>

