---

kms_secrets:
  splunk_password:
    kms: "<kms_encrypted>"
    location: ap-southeast-2
  cloudability_auth_token:
    kms: "<kms_encrypted>"
    location: ap-southeast-2

modules:
  kms_secrets:
    import_path: python_dashing.core_modules.amazon_base.main:AmazonBase

  reviews:
    import_path: custom.reviews.main:Reviews
    server_options:
      app_id: "<app_id>"
      itunes_country_code: au

  scaling:
    import_path: custom.scaling.main:Scaling
    server_options:
      dev_account: "<account_id>"
      stg_account: "<account_id>k"
      prod_account: "<account_id>"
      role_to_assume: role/dashing/viewer
      cloudability_auth_token: "{kms_secrets.cloudability_auth_token}"

dashboards:
  "/":
    jade: |
      p
        a(href="/traffic") Traffic Dashboard
      p
        a(href="/reviews") IOS Reviews Dashboard
      p
        a(href="/scaling") Scaling Groups Dashboard

  "/traffic":
    jade: |
      = "traffic" | module | safe

  "/reviews":
    jade: |
      = "reviews" | module | safe

  "/scaling":
    jade: |
      = "scaling" | module | safe

